# Argon

spacing = 4
padding = 0
hide_ascii = true
prefer_small_ascii = false
separator = ""
key_color = "#EBDBB2"
separator_color = "Yellow"

[palette]
type = "Full"
glyph = "â–ˆâ–ˆâ–“"
visible = true

# [bar]
# glyph           = "ß‹"
# symbol_open     = '['
# symbol_close    = ']'
# visible         = true
# hide_delimiters = false

[box]
title = " System Information ðŸ’» "
border = "double"
visible = true

[box.inner_margin]
x = 3
y = 1

[custom_ascii]
color = "#DDDDDD"
path = "~/.config/macchina/ascii/feyn"

[randomize]
key_color = false
separator_color = false
# pool            = ""

[keys]
host = "User/Hostname"
kernel = "Kernel"
battery = "Battery Info"
os = "Operating System"
de = "Desktop Environment"
wm = "Window Manager"
distro = "Distribution"
terminal = "Terminal Emulator"
shell = "Shell"
packages = "Packages (mgr)"
uptime = "Uptime"
memory = "Memory"
machine = "Machine"
local_ip = "Local IP"
backlight = "Brightness"
resolution = "Resolution"
cpu_load = "CPU Load"
cpu = "Processor (cores)"
gpu = "Graphics Processor"
disk_space = "Disk Space"
