# Boron

spacing = 1
padding = 0
hide_ascii = false
separator = "󰅂"
key_color = "Cyan"
separator_color = "Magenta"

[box]
border = "rounded"
visible = false

[box.inner_margin]
x = 0
y = 0

[custom_ascii]
path = "~/.config/macchina/ascii/cat"
color = "Cyan"

[keys]
kernel = " kr"
wm = " wm"
distro = " os"
shell = " sh"
packages = " pk"
memory = "󰍛 mm"
terminal = " tr"
host = " hs"
machine = " mc"

[palette]
type = "Light"
visible = false
glyph = "󰊠 "
