preload = ~/files/pictures/wallpapers/catscii.png

wallpaper = Virtual-1,~/files/pictures/wallpapers/catscii.png
# ... more monitors

# disable messages on bottom
splash = false

# fully disable ipc
ipc = off
