return {
	-- 	"zk-org/zk-nvim",
	-- 	config = function()
	-- 		require("zk").setup({
	-- 			picker = "telescope",
	-- 			lsp = {
	-- 				config = {
	-- 					cmd = { "zk", "lsp" },
	-- 					name = "zk",
	-- 				},
	-- 				auto_attach = {
	-- 					enabled = true,
	-- 					filetypes = { "markdown" },
	-- 				},
	-- 			},
	-- 		})
	--
	-- 		local map = vim.keymap.set
	-- 		map("n", "<leader>zn", "<cmd>ZkNew { title = vim.fn.input('Title: ') }<CR>", { desc = "[Z]ettel [N]ew Note" })
	-- 		map("n", "<leader>zo", "<cmd>ZkNotes { sort = { 'modified' } }<CR>", { desc = "[Z]ettel [O]pen Notes" })
	-- 		map("n", "<leader>zt", "<cmd>ZkTags<CR>", { desc = "[Z]ettel Search [T]ags" })
	-- 	end,
}
