#!/usr/bin/env fish

if test -z "$MACHINE"
	read -f -P "what is the hostname of the machine to set up?\n> " machine
else
	set -f machine $MACHINE
end

if test -z "$DOTFILES_DIR"
	read -f -P "where is the config repository?\n> " config_location
else
	set -f config_location $DOTFILES_DIR
end

if test -z "$EDITOR"
	# echo "please make sure \$EDITOR is set"
	# exit 1
	echo "it seems \$EDITOR is unset, defaulting to `vi`"
	set -f EDITOR vi
end

switch $argv[1]
	case edit
		switch $argv[2]
			case nixos
				$EDITOR $config_location/nixos/.

			case darwin
				$EDITOR $config_location/darwin/.

			case home
				$EDITOR $config_location/home/.

			case flake
				$EDITOR $config_location/flake.nix

			case script
				$EDITOR $config_location/script

			case ''
				$EDITOR $config_location/.

			case '*'
				$EDITOR $config_location/$argv[2..]
		end

	case switch
		# WARN: these cases be wrong, as i am only sure of macos' uname output
		switch (uname)
			case nix nixos
				nh os switch $config_location -H $machine

			case Darwin
				nh darwin switch $config_location -H $machine

			case linux
				nh home switch $config_location -H $machine

			case '*'
				echo "Unrecognized/unsupported OS."
				exit 1
		end

	case cd
		cd $config_location

	case fzf find
		set current_dir $(pwd)
		cd $config_location
		nvim (fzf)
		cd $current_dir

	case rg search
		rg  --glob=!user-dots $argv[2] $config_location

	case lg git
		lazygit -p $config_location

	case aj fmt format
		alejandra $config_location --exclude $config_location/home/user-dots

	case '*'
		echo "Unrecognized input."
		exit 1
end
