font_family      Space Mono Nerd Font
font_size 18.0

show_hyperlink_targets yes
copy_on_select true

# background_opacity 0.85
background_blur 20
# background_image none

clipboard_control write-clipboard write-primary read-clipboard-ask read-primary-ask

map kitty_mod+u         kitten unicode_input
map kitty_mod+escape    kitty_shell window
map kitty_mod+f5        load_config_file

# MACOS SPECIFIC
macos_option_as_alt yes
macos_quit_when_last_window_closed yes
map cmd+shift+c         copy_to_clipboard
map cmd+shift+v         paste_from_clipboard
map cmd+k               clear_terminal to_cursor active
map cmd+h               hide_macos_app
map opt+cmd+h           hide_macos_other_apps
map cmd+m               minimize_macos_window
map cmd+q               quit

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
