# remap prefix from 'C-b' to 'C-\'
unbind C-b
set-option -g prefix 'C-\'
bind 'C-\' send-prefix

# split panes using | and -
bind | split-window -h
bind _ split-window -v
unbind '"'
unbind %

# reload config file
bind r source-file ~/.config/tmux/tmux.conf

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# set default wd
bind M-c attach-session -c "#{pane_current_path}"

# open new window in current path
bind C new-window -c "#{pane_current_path}"

# don't rename windows automatically
set-option -g allow-rename on

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# switch panes using Alt-hjkl without prefix
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-j select-pane -D
bind -n M-k select-pane -U

# fix tmux and nvim conflicts
set escape-time 0

# set tmux color settings
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# fix yazi image preview
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# change window and pane numbering to start at 1
set -g base-index 1
setw -g pane-base-index 1

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'catppuccin/tmux'

# plugin setup

# swap default session manager for sessionx
unbind 's'
set -g @sessionx-bind 's'

# set catppuccin colors
set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator " | "

set -g @catppuccin_window_default_fill "none"

set -g @catppuccin_window_current_fill "all"

set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_status_modules_right "directory session date_time"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"

set -g @catppuccin_date_time_text "%Y-%m-%d %H:%M:%S"

run '~/.tmux/plugins/tpm/tpm'
