#!/usr/bin/env fish

set filename (string replace -r '\.[^.]*$' '' $argv[1])

pdflatex $filename; and biber $filename; and pdflatex $filename; and clear; and echo "latex compilation of $filename finished"
