#!/bin/zsh

# Check if the user has supplied a session name
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <name of session>"
    exit 1
fi

SESSION_NAME=$1

# Attempt to attach to the session if it exists
if tmux has-session -t $SESSION_NAME 2>/dev/null; then
    echo "Attaching to existing session '$SESSION_NAME'"
    tmux attach-session -t $SESSION_NAME
else
    # If the session doesn't exist, create it
    echo "Creating new session '$SESSION_NAME'"
    tmux new-session -d -s $SESSION_NAME
    tmux attach-session -t $SESSION_NAME
fi
