{
    pkgs,
    ...
}:
{
    environment.systemPackages = with pkgs; [
        # cli/term tools
        asciinema
        asciinema-scenario
        cloudflared
        cht-sh
        dust
        ffmpeg
        fx
        glow
        grex
        gtrash
        gum
        hexyl
        hyperfine
        lazysql
        mkalias
        p7zip
        pastel
        procs
        pngpaste
        poppler-utils
        presenterm
        pv
        testdisk
        tokei
        viu
        wiki-tui
    ];
}
