colors:
  body: none
  date: black
  tags: magenta
  title: cyan
default_hour: 7
default_minute: 30
editor: lvim
encrypt: false
highlight: true
indent_character: '|'
journals:
  default: ~/files/jrnl/journal.txt
  school: ~/files/jrnl/school.txt
  personal: ~/files/jrnl/personal.txt
linewrap: 80
tagsymbols: '#@'
template: false
timeformat: '%F %r'
version: v4.1
