[Setting]
spotify_path            = /Applications/Spotify.app/Contents/Resources
color_scheme            = default
overwrite_assets        = 0
spotify_launch_flags    = 
check_spicetify_upgrade = 0
prefs_path              = /Users/vsrivastava/Library/Application Support/Spotify/prefs
current_theme           = default
inject_theme_js         = 1
inject_css              = 1
replace_colors          = 1
check_spicetify_update  = 1
always_enable_devtools  = 0

[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

[AdditionalOptions]
experimental_features = 1
extensions            = popupLyrics.js|shuffle+.js
custom_apps           = marketplace|lyrics-plus
sidebar_config        = 1
home_config           = 1

[Patch]
xpui.js_find_0880 = COLLAPSED\?64:32
xpui.js_repl_0880 = COLLAPSED?32:32
xpui.js_find_8008 = ,(\w+=)56,
xpui.js_repl_8008 = ,${1}32,

; DO NOT CHANGE!
[Backup]
version           = 1.2.31.1205.g4d59ad7c
with              = 2.33.2
xpui.js_find_8008 = ,(\w+=)56,
xpui.js_repl_8008 = ,${1}32,
